/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.zahid;

import java.time.LocalDateTime;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        LocalDateTime currentTime = LocalDateTime.now();
        System.out.println("The current time is " + currentTime);
    }
}
